// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SeaCodeBase/urlshortener/internal/service (interfaces: ShortCodeService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_shortcode_service.go -package=mocks . ShortCodeService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockShortCodeService is a mock of ShortCodeService interface.
type MockShortCodeService struct {
	ctrl     *gomock.Controller
	recorder *MockShortCodeServiceMockRecorder
	isgomock struct{}
}

// MockShortCodeServiceMockRecorder is the mock recorder for MockShortCodeService.
type MockShortCodeServiceMockRecorder struct {
	mock *MockShortCodeService
}

// NewMockShortCodeService creates a new mock instance.
func NewMockShortCodeService(ctrl *gomock.Controller) *MockShortCodeService {
	mock := &MockShortCodeService{ctrl: ctrl}
	mock.recorder = &MockShortCodeServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShortCodeService) EXPECT() *MockShortCodeServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockShortCodeService) Generate(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Generate indicates an expected call of Generate.
func (mr *MockShortCodeServiceMockRecorder) Generate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockShortCodeService)(nil).Generate), ctx)
}

// IsAvailable mocks base method.
func (m *MockShortCodeService) IsAvailable(ctx context.Context, code string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAvailable", ctx, code)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAvailable indicates an expected call of IsAvailable.
func (mr *MockShortCodeServiceMockRecorder) IsAvailable(ctx, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAvailable", reflect.TypeOf((*MockShortCodeService)(nil).IsAvailable), ctx, code)
}

// IsValid mocks base method.
func (m *MockShortCodeService) IsValid(code string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsValid", code)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsValid indicates an expected call of IsValid.
func (mr *MockShortCodeServiceMockRecorder) IsValid(code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsValid", reflect.TypeOf((*MockShortCodeService)(nil).IsValid), code)
}
