// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SeaCodeBase/urlshortener/internal/service (interfaces: StatsService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_stats_service.go -package=mocks . StatsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/SeaCodeBase/urlshortener/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockStatsService is a mock of StatsService interface.
type MockStatsService struct {
	ctrl     *gomock.Controller
	recorder *MockStatsServiceMockRecorder
	isgomock struct{}
}

// MockStatsServiceMockRecorder is the mock recorder for MockStatsService.
type MockStatsServiceMockRecorder struct {
	mock *MockStatsService
}

// NewMockStatsService creates a new mock instance.
func NewMockStatsService(ctrl *gomock.Controller) *MockStatsService {
	mock := &MockStatsService{ctrl: ctrl}
	mock.recorder = &MockStatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStatsService) EXPECT() *MockStatsServiceMockRecorder {
	return m.recorder
}

// GetLinkStats mocks base method.
func (m *MockStatsService) GetLinkStats(ctx context.Context, userID, linkID uint64) (*service.LinkStatsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkStats", ctx, userID, linkID)
	ret0, _ := ret[0].(*service.LinkStatsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkStats indicates an expected call of GetLinkStats.
func (mr *MockStatsServiceMockRecorder) GetLinkStats(ctx, userID, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkStats", reflect.TypeOf((*MockStatsService)(nil).GetLinkStats), ctx, userID, linkID)
}
