// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SeaCodeBase/urlshortener/internal/repository (interfaces: PasskeyRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_passkey_repo.go -package=mocks . PasskeyRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SeaCodeBase/urlshortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockPasskeyRepository is a mock of PasskeyRepository interface.
type MockPasskeyRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPasskeyRepositoryMockRecorder
	isgomock struct{}
}

// MockPasskeyRepositoryMockRecorder is the mock recorder for MockPasskeyRepository.
type MockPasskeyRepositoryMockRecorder struct {
	mock *MockPasskeyRepository
}

// NewMockPasskeyRepository creates a new mock instance.
func NewMockPasskeyRepository(ctrl *gomock.Controller) *MockPasskeyRepository {
	mock := &MockPasskeyRepository{ctrl: ctrl}
	mock.recorder = &MockPasskeyRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPasskeyRepository) EXPECT() *MockPasskeyRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockPasskeyRepository) CountByUserID(ctx context.Context, userID uint64) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockPasskeyRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockPasskeyRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockPasskeyRepository) Create(ctx context.Context, passkey *model.Passkey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, passkey)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPasskeyRepositoryMockRecorder) Create(ctx, passkey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPasskeyRepository)(nil).Create), ctx, passkey)
}

// Delete mocks base method.
func (m *MockPasskeyRepository) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPasskeyRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPasskeyRepository)(nil).Delete), ctx, id)
}

// GetByCredentialID mocks base method.
func (m *MockPasskeyRepository) GetByCredentialID(ctx context.Context, credentialID []byte) (*model.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCredentialID", ctx, credentialID)
	ret0, _ := ret[0].(*model.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCredentialID indicates an expected call of GetByCredentialID.
func (mr *MockPasskeyRepositoryMockRecorder) GetByCredentialID(ctx, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCredentialID", reflect.TypeOf((*MockPasskeyRepository)(nil).GetByCredentialID), ctx, credentialID)
}

// ListByUserID mocks base method.
func (m *MockPasskeyRepository) ListByUserID(ctx context.Context, userID uint64) ([]model.Passkey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]model.Passkey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockPasskeyRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockPasskeyRepository)(nil).ListByUserID), ctx, userID)
}

// UpdateCounter mocks base method.
func (m *MockPasskeyRepository) UpdateCounter(ctx context.Context, id uint64, counter uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCounter", ctx, id, counter)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockPasskeyRepositoryMockRecorder) UpdateCounter(ctx, id, counter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockPasskeyRepository)(nil).UpdateCounter), ctx, id, counter)
}

// UpdateLastUsedAt mocks base method.
func (m *MockPasskeyRepository) UpdateLastUsedAt(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastUsedAt", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastUsedAt indicates an expected call of UpdateLastUsedAt.
func (mr *MockPasskeyRepositoryMockRecorder) UpdateLastUsedAt(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastUsedAt", reflect.TypeOf((*MockPasskeyRepository)(nil).UpdateLastUsedAt), ctx, id)
}

// UpdateName mocks base method.
func (m *MockPasskeyRepository) UpdateName(ctx context.Context, id uint64, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateName", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateName indicates an expected call of UpdateName.
func (mr *MockPasskeyRepositoryMockRecorder) UpdateName(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateName", reflect.TypeOf((*MockPasskeyRepository)(nil).UpdateName), ctx, id, name)
}
