// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SeaCodeBase/urlshortener/internal/repository (interfaces: DomainRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_domain_repo.go -package=mocks . DomainRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SeaCodeBase/urlshortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockDomainRepository is a mock of DomainRepository interface.
type MockDomainRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDomainRepositoryMockRecorder
	isgomock struct{}
}

// MockDomainRepositoryMockRecorder is the mock recorder for MockDomainRepository.
type MockDomainRepositoryMockRecorder struct {
	mock *MockDomainRepository
}

// NewMockDomainRepository creates a new mock instance.
func NewMockDomainRepository(ctrl *gomock.Controller) *MockDomainRepository {
	mock := &MockDomainRepository{ctrl: ctrl}
	mock.recorder = &MockDomainRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDomainRepository) EXPECT() *MockDomainRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDomainRepository) Create(ctx context.Context, domain *model.Domain) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, domain)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDomainRepositoryMockRecorder) Create(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDomainRepository)(nil).Create), ctx, domain)
}

// Delete mocks base method.
func (m *MockDomainRepository) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDomainRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDomainRepository)(nil).Delete), ctx, id)
}

// GetByDomain mocks base method.
func (m *MockDomainRepository) GetByDomain(ctx context.Context, domain string) (*model.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDomain", ctx, domain)
	ret0, _ := ret[0].(*model.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDomain indicates an expected call of GetByDomain.
func (mr *MockDomainRepositoryMockRecorder) GetByDomain(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDomain", reflect.TypeOf((*MockDomainRepository)(nil).GetByDomain), ctx, domain)
}

// GetByID mocks base method.
func (m *MockDomainRepository) GetByID(ctx context.Context, id uint64) (*model.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockDomainRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDomainRepository)(nil).GetByID), ctx, id)
}

// ListByUserID mocks base method.
func (m *MockDomainRepository) ListByUserID(ctx context.Context, userID uint64) ([]*model.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]*model.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockDomainRepositoryMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockDomainRepository)(nil).ListByUserID), ctx, userID)
}
