// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SeaCodeBase/urlshortener/internal/repository (interfaces: LinkRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_link_repo.go -package=mocks . LinkRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SeaCodeBase/urlshortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLinkRepository is a mock of LinkRepository interface.
type MockLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockLinkRepositoryMockRecorder is the mock recorder for MockLinkRepository.
type MockLinkRepositoryMockRecorder struct {
	mock *MockLinkRepository
}

// NewMockLinkRepository creates a new mock instance.
func NewMockLinkRepository(ctrl *gomock.Controller) *MockLinkRepository {
	mock := &MockLinkRepository{ctrl: ctrl}
	mock.recorder = &MockLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkRepository) EXPECT() *MockLinkRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockLinkRepository) CountByUserID(ctx context.Context, userID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockLinkRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockLinkRepository)(nil).CountByUserID), ctx, userID)
}

// Create mocks base method.
func (m *MockLinkRepository) Create(ctx context.Context, link *model.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLinkRepositoryMockRecorder) Create(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLinkRepository)(nil).Create), ctx, link)
}

// Delete mocks base method.
func (m *MockLinkRepository) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLinkRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLinkRepository)(nil).Delete), ctx, id)
}

// GetByDomainAndShortCode mocks base method.
func (m *MockLinkRepository) GetByDomainAndShortCode(ctx context.Context, domainID *uint64, shortCode string) (*model.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByDomainAndShortCode", ctx, domainID, shortCode)
	ret0, _ := ret[0].(*model.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByDomainAndShortCode indicates an expected call of GetByDomainAndShortCode.
func (mr *MockLinkRepositoryMockRecorder) GetByDomainAndShortCode(ctx, domainID, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByDomainAndShortCode", reflect.TypeOf((*MockLinkRepository)(nil).GetByDomainAndShortCode), ctx, domainID, shortCode)
}

// GetByID mocks base method.
func (m *MockLinkRepository) GetByID(ctx context.Context, id uint64) (*model.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockLinkRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockLinkRepository)(nil).GetByID), ctx, id)
}

// ListByUserID mocks base method.
func (m *MockLinkRepository) ListByUserID(ctx context.Context, userID uint64, limit, offset int) ([]model.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]model.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockLinkRepositoryMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockLinkRepository)(nil).ListByUserID), ctx, userID, limit, offset)
}

// ShortCodeExistsInDomain mocks base method.
func (m *MockLinkRepository) ShortCodeExistsInDomain(ctx context.Context, domainID *uint64, shortCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShortCodeExistsInDomain", ctx, domainID, shortCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShortCodeExistsInDomain indicates an expected call of ShortCodeExistsInDomain.
func (mr *MockLinkRepositoryMockRecorder) ShortCodeExistsInDomain(ctx, domainID, shortCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShortCodeExistsInDomain", reflect.TypeOf((*MockLinkRepository)(nil).ShortCodeExistsInDomain), ctx, domainID, shortCode)
}

// Update mocks base method.
func (m *MockLinkRepository) Update(ctx context.Context, link *model.Link) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, link)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLinkRepositoryMockRecorder) Update(ctx, link any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLinkRepository)(nil).Update), ctx, link)
}
