// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/SeaCodeBase/urlshortener/internal/repository (interfaces: ClickRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_click_repo.go -package=mocks . ClickRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/SeaCodeBase/urlshortener/internal/model"
	repository "github.com/SeaCodeBase/urlshortener/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockClickRepository is a mock of ClickRepository interface.
type MockClickRepository struct {
	ctrl     *gomock.Controller
	recorder *MockClickRepositoryMockRecorder
	isgomock struct{}
}

// MockClickRepositoryMockRecorder is the mock recorder for MockClickRepository.
type MockClickRepositoryMockRecorder struct {
	mock *MockClickRepository
}

// NewMockClickRepository creates a new mock instance.
func NewMockClickRepository(ctrl *gomock.Controller) *MockClickRepository {
	mock := &MockClickRepository{ctrl: ctrl}
	mock.recorder = &MockClickRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClickRepository) EXPECT() *MockClickRepositoryMockRecorder {
	return m.recorder
}

// BatchInsert mocks base method.
func (m *MockClickRepository) BatchInsert(ctx context.Context, clicks []model.Click) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchInsert", ctx, clicks)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchInsert indicates an expected call of BatchInsert.
func (mr *MockClickRepositoryMockRecorder) BatchInsert(ctx, clicks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchInsert", reflect.TypeOf((*MockClickRepository)(nil).BatchInsert), ctx, clicks)
}

// GetBrowserStats mocks base method.
func (m *MockClickRepository) GetBrowserStats(ctx context.Context, linkID uint64) ([]repository.BrowserStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBrowserStats", ctx, linkID)
	ret0, _ := ret[0].([]repository.BrowserStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBrowserStats indicates an expected call of GetBrowserStats.
func (mr *MockClickRepositoryMockRecorder) GetBrowserStats(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBrowserStats", reflect.TypeOf((*MockClickRepository)(nil).GetBrowserStats), ctx, linkID)
}

// GetDailyStats mocks base method.
func (m *MockClickRepository) GetDailyStats(ctx context.Context, linkID uint64, days int) ([]repository.DailyClickStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDailyStats", ctx, linkID, days)
	ret0, _ := ret[0].([]repository.DailyClickStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDailyStats indicates an expected call of GetDailyStats.
func (mr *MockClickRepositoryMockRecorder) GetDailyStats(ctx, linkID, days any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDailyStats", reflect.TypeOf((*MockClickRepository)(nil).GetDailyStats), ctx, linkID, days)
}

// GetDeviceStats mocks base method.
func (m *MockClickRepository) GetDeviceStats(ctx context.Context, linkID uint64) ([]repository.DeviceStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceStats", ctx, linkID)
	ret0, _ := ret[0].([]repository.DeviceStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceStats indicates an expected call of GetDeviceStats.
func (mr *MockClickRepositoryMockRecorder) GetDeviceStats(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceStats", reflect.TypeOf((*MockClickRepository)(nil).GetDeviceStats), ctx, linkID)
}

// GetStatsByLinkID mocks base method.
func (m *MockClickRepository) GetStatsByLinkID(ctx context.Context, linkID uint64) (*repository.ClickStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatsByLinkID", ctx, linkID)
	ret0, _ := ret[0].(*repository.ClickStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatsByLinkID indicates an expected call of GetStatsByLinkID.
func (mr *MockClickRepositoryMockRecorder) GetStatsByLinkID(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatsByLinkID", reflect.TypeOf((*MockClickRepository)(nil).GetStatsByLinkID), ctx, linkID)
}

// GetTopReferrers mocks base method.
func (m *MockClickRepository) GetTopReferrers(ctx context.Context, linkID uint64, limit int) ([]repository.ReferrerStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopReferrers", ctx, linkID, limit)
	ret0, _ := ret[0].([]repository.ReferrerStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopReferrers indicates an expected call of GetTopReferrers.
func (mr *MockClickRepositoryMockRecorder) GetTopReferrers(ctx, linkID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopReferrers", reflect.TypeOf((*MockClickRepository)(nil).GetTopReferrers), ctx, linkID, limit)
}

// GetTotalByLinkID mocks base method.
func (m *MockClickRepository) GetTotalByLinkID(ctx context.Context, linkID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTotalByLinkID", ctx, linkID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTotalByLinkID indicates an expected call of GetTotalByLinkID.
func (mr *MockClickRepositoryMockRecorder) GetTotalByLinkID(ctx, linkID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTotalByLinkID", reflect.TypeOf((*MockClickRepository)(nil).GetTotalByLinkID), ctx, linkID)
}
